config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: "oauth/applications",
                authorized_applications: "oauth/authorized_applications"
  end

  resources :comments
  resources :devices
  resources :teams

  if Setting.has_module?(:home)
    root to: "home#index"
  else
    root to: "topics#index"
  end
  match "/uploads/:path(![large|lg|md|sm|xs])", to: "home#uploads", via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: "auth/omniauth_callbacks"
  }

  resource :setting do
    member do
      get :account
      get :password
      get :profile
      get :reward
    end
  end

  # SSO
  namespace :auth do
    resource :sso, controller: "sso" do
      collection do
        get :login
        get :provider
      end
    end
  end

  delete "setting/auth/:provider", to: "settings#auth_unbind"

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get "topics/node:id", to: "topics#node", as: "node_topics"
  get "topics/node:id/feed", to: "topics#node_feed", as: "feed_node_topics", defaults: { format: "xml" }

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
      # ban popup window
      get :ban
    end

    collection do
      get :no_reply
      get :popular
      get :last
      get :last_reply
      get :banned
      get :excellent
      get :favorites
      get :feed, defaults: { format: "xml" }
      post :preview
    end

    resources :replies do
      member do
        get :reply_to
      end
    end
  end

  resources :photos
  resources :likes

  get "/search", to: "search#index", as: "search"
  get "/search/users", to: "search#users", as: "search_users"

  namespace :admin do
    root to: "home#index", as: "root"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :comments
    resources :locations
    resources :applications
    resources :stats
  end

  get "api", to: "home#api", as: "api"
  get "markdown", to: "home#markdown", as: "markdown"

  namespace :api do
    namespace :v3 do
      get "hello", to: "root#hello"

      resource :devices
      resource :likes
      resources :nodes
      resources :photos
      resources :notifications do
        collection do
          post :read
          get :unread_count
          delete :all
        end
      end
      resources :topics do
        member do
          post :update
          get :replies
          post :replies
          post :follow
          post :unfollow
          post :favorite
          post :unfavorite
          post :ban
          post :action
        end
      end
      resources :replies do
        member do
          post :update
        end
      end
      resources :users do
        collection do
          get :me
        end
        member do
          get :topics
          get :replies
          get :favorites
          get :followers
          get :following
          get :blocked
          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end

      match "*path", to: "root#not_found", via: :all
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "sidekiq"
    mount PgHero::Engine, at: "pghero"
    mount ExceptionTrack::Engine, at: "exception-track"
  end

  mount Notifications::Engine, at: "notifications"
  mount StatusPage::Engine, at: "/"

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"

  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users" do
      member do
        # User only
        get :topics
        get :replies
        get :favorites
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
        get :reward
      end

      resources :team_users, path: "people" do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match "*path", to: "home#error_404", via: :all
end

app/controllers/admin/topics_controller.rb
# frozen_string_literal: true

module Admin
  class TopicsController < Admin::ApplicationController
    before_action :set_topic, only: %i[show edit update destroy undestroy suggest unsuggest]

    def index
      @topics = Topic.unscoped
      if params[:q].present?
        qstr = "%#{params[:q].downcase}%"
        @topics = @topics.where("title LIKE ?", qstr)
      end
      if params[:login].present?
        u = User.find_by_login(params[:login])
        @topics = @topics.where("user_id = ?", u.try(:id))
      end
      @topics = @topics.order(id: :desc)
      @topics = @topics.includes(:user).page(params[:page])
    end

    def show
    end

    def new
      @topic = Topic.new
    end

    def edit
    end

    def create
      @topic = Topic.new(params[:topic].permit!)

      if @topic.save
        redirect_to(admin_topics_path, notice: "Topic was successfully created.")
      else
        render action: "new"
      end
    end

    def update
      if @topic.update(params[:topic].permit!)
        redirect_to(admin_topics_path, notice: "Topic was successfully updated.")
      else
        render action: "edit"
      end
    end

    def destroy
      @topic.destroy_by(current_user)

      redirect_to(admin_topics_path)
    end

    def undestroy
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(admin_topics_path)
    end

    def suggest
      @topic.update_attribute(:suggested_at, Time.now)
      redirect_to(@topic, notice: "Topic:#{params[:id]} suggested.")
    end

    def unsuggest
      @topic.update_attribute(:suggested_at, nil)
      redirect_to(@topic, notice: "Topic:#{params[:id]} unsuggested.")
    end

    private

      def set_topic
        @topic = Topic.unscoped.find(params[:id])
      end
  end
end

app/controllers/api/v3/topics_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class TopicsController < Api::V3::ApplicationController
      before_action :doorkeeper_authorize!, except: %i[index show replies]
      before_action :set_topic, except: %i[index create]

      # 获取话题列表，类似网站的 /topics 的结构，支持多种排序方式。
      #
      # GET /api/v3/topics
      #
      # @param type [String] 排序类型, default: `last_actived`, %w(last_actived recent no_reply popular excellent)
      # @param node_id [Integer] 节点编号，如果有给，就会只去节点下的话题
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      #
      # @return [Array<TopicSerializer>]
      def index
        optional! :type, default: "last_actived"
        optional! :node_id
        optional! :offset, default: 0
        optional! :limit, default: 20, values: 1..150

        params[:type] = params[:type].downcase

        if params[:node_id].blank?
          @topics = Topic
          if current_user
            @topics = @topics.without_nodes(current_user.block_node_ids)
            @topics = @topics.without_users(current_user.block_user_ids)
          else
            @topics = @topics.without_hide_nodes
          end
        else
          @node = Node.find(params[:node_id])
          @topics = @node.topics
        end

        @topics = @topics.without_ban.fields_for_list.includes(:user).send(scope_method_by_type)
        if %w[no_reply popular].index(params[:type])
          @topics = @topics.last_actived
        elsif params[:type] == "excellent"
          @topics = @topics.recent
        end

        @topics = @topics.offset(params[:offset]).limit(params[:limit])
      end

      # 获取话题详情（不含回帖）
      #
      # GET /api/v3/topics/:id
      #
      # @param id [Integer] 话题编号
      # @return [TopicDetailSerializer] 此外 meta 里面包含当前用户对此话题的状态
      #
      # ```json
      # { followed: '是否已关注', liked: '是否已赞', favorited: '是否已收藏' }
      # ```
      def show
        @topic.hits.incr(1)
        @meta = { followed: false, liked: false, favorited: false }

        if current_user
          # 处理通知
          current_user.read_topic(@topic)
          @meta[:followed] = current_user.follow_topic?(@topic)
          @meta[:liked] = current_user.like_topic?(@topic)
          @meta[:favorited] = current_user.favorite_topic?(@topic)
        end
      end

      # 创建新话题
      #
      # POST /api/v3/topics
      #
      # @param title [String] 标题, [required]
      # @param node_id [Integer] 节点编号, [required]
      # @param body [Markdown] 格式的正文, [required]
      # @return [TopicDetailSerializer]
      def create
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied.new("当前登录的用户没有发帖权限，具体请参考官网的相关说明。") unless can?(:create, Topic)

        @topic = current_user.topics.new(title: params[:title], body: params[:body])
        @topic.node_id = params[:node_id]
        @topic.save!

        render "show"
      end

      # 更新话题
      #
      # POST /api/v3/topics/:id
      #
      # @param title [String] 标题, [required]
      # @param node_id [Integer] 节点编号, [required]
      # @param body [String] Markdown 格式的正文, [required]
      # @return [TopicDetailSerializer]
      def update
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied unless can?(:update, @topic)

        if @topic.lock_node == false || admin?
          # 锁定接点的时候，只有管理员可以修改节点
          @topic.node_id = params[:node_id]

          if admin? && @topic.node_id_changed?
            # 当管理员修改节点的时候，锁定节点
            @topic.lock_node = true
          end
        end
        @topic.title = params[:title]
        @topic.body = params[:body]
        @topic.save!

        render "show"
      end

      # 删除话题
      #
      # DELETE /api/v3/topics/:id
      def destroy
        raise AccessDenied unless can?(:destroy, @topic)
        @topic.destroy_by(current_user)
        render json: { ok: 1 }
      end

      # 获取话题的回帖列表
      #
      # GET /api/v3/topics/:id/replies
      #
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      # @return [Array<ReplySerializer]>
      def replies
        if request.post?
          create_replies
          return
        end

        params[:limit] ||= 20

        @replies = Reply.unscoped.where(topic_id: @topic.id).order(:id).includes(:user)
        @replies = @replies.offset(params[:offset].to_i).limit(params[:limit].to_i)
        @user_liked_reply_ids = current_user&.like_reply_ids_by_replies(@replies) || []
        @meta = { user_liked_reply_ids: @user_liked_reply_ids }
      end

      # 创建对话题的回帖
      #
      # POST /api/v3/topics/:id/replies
      #
      # @param body [String] 回帖内容，[required]
      # @return [ReplySerializer] 创建的回帖信息
      def create_replies
        doorkeeper_authorize!

        requires! :body

        raise AccessDenied.new("当前用户没有回帖权限，具体请参考官网的说明。") unless can?(:create, Reply)

        @reply = @topic.replies.build(body: params[:body])
        @reply.user_id = current_user.id
        @reply.save!
        render "api/v3/replies/show"
      end

      # 关注话题
      #
      # POST /api/v3/topics/:id/follow
      def follow
        current_user.follow_topic(@topic)
        render json: { ok: 1 }
      end

      # 取消关注话题
      #
      # POST /api/v3/topics/:id/unfollow
      def unfollow
        current_user.unfollow_topic(@topic)
        render json: { ok: 1 }
      end

      # 收藏话题
      #
      # POST /api/v3/topics/:id/favorite
      def favorite
        current_user.favorite_topic(@topic.id)
        render json: { ok: 1 }
      end

      # 取消收藏话题
      #
      # POST /api/v3/topics/:id/unfavorite
      def unfavorite
        current_user.unfavorite_topic(@topic.id)
        render json: { ok: 1 }
      end

      # 屏蔽话题 (Admin only)
      # [废弃] 请用 POST /api/v3/topics/:id/action
      #
      # POST /api/v3/topics/:id/ban
      def ban
        raise AccessDenied.new("当前用户没有屏蔽别人话题的权限，具体请参考官网的说明。") unless can?(:ban, @topic)
        @topic.ban!
        render json: { ok: 1 }
      end

      # 更多功能
      # 注意类型有不同的权限，详见 GET /api/v3/topics/:id 返回的 abilities
      #
      # POST /api/v3/topics/:id/action?type=:type
      # @param type [String] 动作类型, ban - 屏蔽话题, normal - 取消屏蔽, excellent - 加精华, unexcellent - 取消精华, close - 关闭回复, open - 开启回复
      def action
        raise AccessDenied unless can?(params[:type].to_sym, @topic)

        case params[:type]
        when "excellent"
          @topic.excellent!
        when "unexcellent"
          @topic.unexcellent!
        when "normal"
          @topic.normal!
        when "ban"
          @topic.ban!
        when "close"
          @topic.close!
        when "open"
          @topic.open!
        end
        render json: { ok: 1 }
      end

      private

        def set_topic
          @topic = Topic.find(params[:id])
        end

        def scope_method_by_type
          case params[:type]
          when "last_actived" then :last_actived
          when "recent" then :recent
          when "no_reply" then :no_reply
          when "popular" then :popular
          when "excellent" then :excellent
          else
            :last_actived
          end
        end
    end
  end
end

app/controllers/topics/list_actions.rb
# frozen_string_literal: true

module Topics
  module ListActions
    extend ActiveSupport::Concern

    included do
    end

    # GET /topics/popular
    # GET /topics/no_reply
    %i[no_reply popular].each do |name|
      define_method(name) do
        @topics = topics_scope.send(name).last_actived.page(params[:page])

        render_index(name)
      end
    end

    # GET /topics/last_reply
    def last_reply
      @topics = topics_scope.last_reply.page(params[:page])
      render_index("last_reply")
    end

    # GET /topics/favorites
    def favorites
      @topics = topics_scope(current_user.favorite_topics).page(params[:page])
      render_index("favorites")
    end

    # GET /topics/last
    def last
      @topics = topics_scope.recent.page(params[:page])
      render_index("recent")
    end

    # GET /topics/banned
    def banned
      @topics = Topic.ban.recent.page(params[:page])
      render_index("banned")
    end

    # GET /topics/excellent
    def excellent
      @topics = topics_scope.excellent.recent.page(params[:page])
      render_index("excellent")
    end

    private

      def render_index(name)
        @page_title = [t("topics.topic_list.#{name.to_s}"), t("menu.topics")].join(" · ")
        render action: "index"
      end

      def topics_scope(base_scope = Topic, without_nodes: true)
        scope = base_scope.without_ban.fields_for_list
        scope = scope.without_hide_nodes if without_nodes

        if current_user
          scope = scope.without_nodes(current_user.block_node_ids) if without_nodes
          scope = scope.without_users(current_user.block_user_ids)
        end

        # must include :user, because it's uses for _topic.html.erb fragment cache_key
        scope.includes(:user)
      end
  end
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

require "digest/md5"
module TopicsHelper
  def topic_favorite_tag(topic, opts = {})
    return "" if current_user.blank?
    opts[:class] ||= ""
    class_name = ""
    link_title = "收藏"
    if current_user&.favorite_topic?(topic)
      class_name = "active"
      link_title = "取消收藏"
    end

    icon = raw(content_tag("i", "", class: "fa fa-bookmark"))
    if opts[:class].present?
      class_name += " " + opts[:class]
    end

    link_to(raw("#{icon} 收藏"), "#", title: link_title, class: "bookmark #{class_name}", "data-id" => topic.id)
  end

  def topic_follow_tag(topic, opts = {})
    return "" if current_user.blank?
    return "" if topic.blank?
    return "" if owner?(topic)
    opts[:class] ||= ""
    class_name = "follow"
    class_name += " active" if current_user.follow_topic?(topic)
    if opts[:class].present?
      class_name += " " + opts[:class]
    end
    icon = content_tag("i", "", class: "fa fa-eye")
    link_to(raw("#{icon} 关注"), "#", "data-id" => topic.id, class: class_name)
  end

  def topic_title_tag(topic, opts = {})
    return t("topics.topic_was_deleted") if topic.blank?
    if opts[:reply]
      index = topic.floor_of_reply(opts[:reply])
      path = main_app.topic_path(topic, anchor: "reply#{index}")
    else
      path = main_app.topic_path(topic)
    end
    link_to(topic.title, path, title: topic.title)
  end

  def topic_excellent_tag(topic)
    return "" unless topic.excellent?
    content_tag(:i, "", title: "精华帖", class: "fa fa-diamond", data: { toggle: "tooltip" })
  end

  def topic_close_tag(topic)
    return "" unless topic.closed?
    content_tag(:i, "", title: "问题已解决／话题已结束讨论", class: "fa fa-check", data: { toggle: "tooltip" })
  end

  def render_node_name(name, id)
    link_to(name, main_app.node_topics_path(id), class: "node")
  end
end

app/views/topics/_ban.html.erb
<div class="modal" id="ban-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for('', url: action_topic_path(topic, type: "ban"), method: "POST", remote: true) do |f| %>
      <div class="modal-header">
        <div class="modal-title">屏蔽原因</div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <select class="form-control" onchange="$('#ban-modal textarea').val($(this).val())" name="reason">
            <option value="" selected>直接屏蔽</option>
            <% Setting.ban_reason_list.each do |str| %>
            <option value="<%= str %>"><%= str %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <label>或手工输入原因:</label>
          <textarea class="form-control" name="reason_text" rows="4"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">确定</button>
        <a class="btn btn-default" data-dismiss="modal">取消</a>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_buttons.html.erb
<div class="opts">
  <% if !turbolinks_ios? %>
    <%= likeable_tag(@topic) %>
    <%= topic_follow_tag(@topic) %>
    <%= topic_favorite_tag(@topic) %>
  <% end %>

  <% if admin? %>
    <% if !@topic.suggested_at.blank? %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% else %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% end %>
    <% if !@topic.excellent? %>
    <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic.id, type: 'excellent'), title: "设为精华帖" , method: :post, remote: true %>
    <% end %>

    <% if !@topic.ban? %>
      <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), ban_topic_path(@topic), remote: true, title: "全站屏蔽此贴" %>
    <% else %>
      <%= link_to raw("<i class='fa fa-ban'></i> 取消"), action_topic_path(@topic, type: 'normal'), method: :post, remote: true, title: "取消全站屏蔽此贴" %>
    <% end %>
  <% end %>
  <span class="pull-right opts">
    <% if owner?(@topic) or admin? %>
    <% if can?(:close, @topic) %>
      <% if !@topic.closed? %>
        <%= link_to raw("<i class='fa fa-check'></i>"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
      <% else %>
        <%= link_to raw("<i class='fa fa-undo'></i>"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
      <% end %>
    <% end %>
    <%= link_to "", edit_topic_path(@topic), class: "fa fa-pencil", title: "修改本帖" %>
      <% if can?(:destroy, @topic) %>
      <%= link_to "", topic_path(@topic.id), method: :delete, remote: true, 'data-confirm': t("common.confirm_delete"), class: "fa fa-trash", title: "删除本帖" %>
      <% end %>
    <% end %>
  </span>
</div>

app/views/topics/_node_info.html.erb
<% content_for :sub_navbar do %>
  <div class="sub-navbar node-header hide-ios">
    <div class="container">
      <% if !node.blank? %>
        <div class="title">
          <%= node.name %>
          <span class="total">共有 <%= node.topics_count %> 个讨论主题</span>
          <div class="pull-right">
            <% if node.collapse_summary? %>
              <a class="btn btn-sm btn-default" data-toggle="collapse" href="#node-summary"><i class="fa fa-lightbulb-o"></i> 节点介绍</a>
            <% end %>
            <%= block_node_tag(node) %>
          </div>
        </div>
        <div class="summary<%= ' collapse' if node.collapse_summary? %>" id="node-summary">
          <%= sanitize_markdown node.summary_html %>
        </div>

        <% if node.name == '招聘' %>
          <hr />
          <ul class="nav nav-pills prefix-filter">
            <% cache "prefixes", expires_in: 7.days do %>
              <% Location.hot.limit(12).each do |prefix| %>
                <li class="nav-item"><%= link_to prefix.name, homeland_jobs.jobs_path(location: prefix.name), class: "nav-link" %></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      <% else %>
        <%= render 'node_selector' %>
        <ul class="filter nav nav-pills">
          <li><a href="#" class="all-nodes" data-toggle="modal" data-target="#node-selector">所有节点 <span class="caret-right"></span></a></li>
          <li class="<%= ' active' if action_name == 'index' %>">
            <a href="<%= main_app.topics_path %>" data-turbolinks-action="replace">默认</a>
          </li>
          <li class="<%= ' active' if action_name == 'excellent' %>">
            <a href="<%= main_app.excellent_topics_path %>" data-turbolinks-action="replace"><i class="fa fa-diamond"></i> 精华帖</a>
          </li>
          <li class="<%= ' active' if action_name == 'popular' %>">
            <a href="<%= main_app.popular_topics_path %>" data-turbolinks-action="replace">优质帖子</a>
          </li>
          <% if admin? %>
          <li class="<%= ' active' if action_name == 'banned' %>">
            <%= link_to('已屏蔽', main_app.banned_topics_path, data: { 'turbolinks-action': 'replace' }) %>
          </li>
          <% end %>
          <% if !mobile? %>
          <li class="<%= ' active' if action_name == 'no_reply' %>">
            <%= link_to('无人问津', main_app.no_reply_topics_path, data: { 'turbolinks-action': 'replace' }) %>
          </li>
          <li class="<%= ' active' if action_name == 'last_reply' %>">
            <%= link_to('最新回复', main_app.last_reply_topics_path, data: { 'turbolinks-action': 'replace' }) %>
          </li>
          <% end %>
          <li class="<%= ' active' if action_name == 'last' %>">
            <%= link_to('最新发布', main_app.last_topics_path, data: { 'turbolinks-action': 'replace' }) %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/topics/_reply_form.html.erb
<%= render "/shared/editor_toolbar" %>
<%= form_with(model: Reply.new, remote: true, url: topic_replies_path(@topic), id: "new_reply") do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control", rows: "4", tabindex: "1" %>
  </div>
  <%= f.hidden_field :reply_to_id %>
  <div class="submit-buttons">
    <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2", data-disable-with='<%= t("topics.submit_reply") %>'><%= t("topics.submit_reply")%></button>
    <span class="help-inline" style="padding-left: 5px;" title="或者 Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

    <div class="pull-right"><a href="/markdown" target="_blank">排版说明</a></div>
  </div>
<% end %>

app/views/topics/_topic_sidebar.html.erb
<div id="topic-sidebar" data-spy="affix" data-offset-bottom="65">
  <div class="card">
    <div class="card-body">
      <a href="#" class="btn btn-default btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
      <div class="buttons">
        <div class="group likes opts">
          <%= likeable_tag(@topic) %>
        </div>
        <div class="group">
          <div class="btn-group" role="group">
            <%= topic_follow_tag(@topic, class: 'btn btn-default') %>
            <%= topic_favorite_tag(@topic, class: 'btn btn-default') %>
          </div>
        </div>
      </div>
      <hr />
      <div class="group">
        <%= social_share_button_tag h("#{@topic.title}") %>
      </div>
      <hr />
      <div class="reply-buttons">
        <div class="total">
          共收到 <b><%= @topic.replies_count %></b> 条回复
        </div>
        <%= reward_user_tag(@topic.user) %>
      </div>
      <hr />
      <div class="group opts">
        <% if admin? %>
          <div style="margin-bottom: 8px">
            <% if !@topic.suggested_at.blank? %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% else %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% end %>
            <% if !@topic.excellent? %>
            <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic, type: 'excellent'), method: "post", remote: true %>
            <% end %>

            <% if !@topic.ban? %>
              <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), ban_topic_path(@topic), remote: true, title: "全站屏蔽此贴" %>
            <% else %>
              <%= link_to raw("<i class='fa fa-ban'></i> 取消"), action_topic_path(@topic, type: 'normal'), method: :post, remote: true, title: "取消全站屏蔽此贴" %>
            <% end %>
          </div>
        <% end %>

        <% if owner?(@topic) or admin? %>
        <div>
          <% if can?(:close, @topic) %>
            <% if !@topic.closed? %>
              <%= link_to raw("<i class='fa fa-check'></i> 结束"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
            <% else %>
              <%= link_to raw("<i class='fa fa-undo'></i> 开启"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
            <% end %>
          <% end %>
          <%= link_to raw('<i class="fa fa-pencil"></i> 编辑'), edit_topic_path(@topic), title: "修改本帖" %>
          <% if can?(:destroy, @topic) %>
            <%= link_to raw('<i class="fa fa-trash"></i> 删除'), topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), title: "删除本帖", remote: true %>
          <% end %>
        </div>
        <% end %>
      </div>
      <a href="#" class="btn btn-default btn-sm btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  </div>

  <div class="notify-updated">
    <a class="update" href="#"><i class="fa fa-bell-o"></i> <b>有新回复！</b>点击这里立即载入</a>
  </div>
</div>

app/views/topics/ban.js.erb
$('#ban-modal').remove();
$('body').append("<%= j(render('ban', topic: @topic)) %>");
$('#ban-modal').modal();