config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: "oauth/applications",
                authorized_applications: "oauth/authorized_applications"
  end

  resources :comments
  resources :devices
  resources :teams

  if Setting.has_module?(:home)
    root to: "home#index"
  else
    root to: "topics#index"
  end
  match "/uploads/:path(![large|lg|md|sm|xs])", to: "home#uploads", via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: "auth/omniauth_callbacks"
  }

  resource :setting do
    member do
      get :account
      get :password
      get :profile
      get :reward
    end
  end

  # SSO
  namespace :auth do
    resource :sso, controller: "sso" do
      collection do
        get :login
        get :provider
      end
    end
  end

  delete "setting/auth/:provider", to: "settings#auth_unbind"

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get "topics/node:id", to: "topics#node", as: "node_topics"
  get "topics/node:id/feed", to: "topics#node_feed", as: "feed_node_topics", defaults: { format: "xml" }

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
      # ban popup window
      get :ban
    end

    collection do
      get :no_reply
      get :popular
      get :last
      get :last_reply
      get :banned
      get :excellent
      get :favorites
      get :feed, defaults: { format: "xml" }
      post :preview
    end

    resources :replies do
      member do
        get :reply_to
      end
    end
  end

  resources :photos
  resources :likes

  get "/search", to: "search#index", as: "search"
  get "/search/users", to: "search#users", as: "search_users"

  namespace :admin do
    root to: "home#index", as: "root"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :comments
    resources :locations
    resources :applications
    resources :stats
  end

  get "api", to: "home#api", as: "api"
  get "markdown", to: "home#markdown", as: "markdown"

  namespace :api do
    namespace :v3 do
      get "hello", to: "root#hello"

      resource :devices
      resource :likes
      resources :nodes
      resources :photos
      resources :notifications do
        collection do
          post :read
          get :unread_count
          delete :all
        end
      end
      resources :topics do
        member do
          post :update
          get :replies
          post :replies
          post :follow
          post :unfollow
          post :favorite
          post :unfavorite
          post :ban
          post :action
        end
      end
      resources :replies do
        member do
          post :update
        end
      end
      resources :users do
        collection do
          get :me
        end
        member do
          get :topics
          get :replies
          get :favorites
          get :followers
          get :following
          get :blocked
          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end

      match "*path", to: "root#not_found", via: :all
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "sidekiq"
    mount PgHero::Engine, at: "pghero"
    mount ExceptionTrack::Engine, at: "exception-track"
  end

  mount Notifications::Engine, at: "notifications"
  mount StatusPage::Engine, at: "/"

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"

  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users" do
      member do
        # User only
        get :topics
        get :replies
        get :favorites
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
        get :reward
      end

      resources :team_users, path: "people" do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match "*path", to: "home#error_404", via: :all
end

app/views/shared/_comment.html.erb
<div class="comment media">
  <div class="avatar media-left mr-3">
    <%= user_avatar_tag(comment.user, :md) %>
  </div>
  <div class="media-body">
    <div class="info media-heading mb-2">
      <span class="name"><%= user_name_tag(comment.user) %></span> 发表于 <%= timeago(comment.created_at) %>
    </div>
    <div class="body markdown">
      <%= comment.body_html %>
    </div>
  </div>
</div>

app/views/shared/_comments.html.erb
<%
comments = Comment.where(commentable_type: commentable.class.name, commentable_id: commentable.id).includes(:user)
new_comment = Comment.new(commentable_type: commentable.class.name, commentable_id: commentable.id)
%>

<div id="<%= commentable.class.name %>_<%= commentable.id %>_cell_comments" class="comments card">
  <div class="card-header">评论列表</div>
  <div class="card-body">
    <% if !comments.blank? %>
    <%= render :partial => "/shared/comment", :collection => comments %>
    <% else %>
    <div class="no-result"><%= t("comments.no_comment") %>.</div>
    <% end %>
  </div>
</div>

<% if @current_user %>
  <div id="<%= commentable.class.name %>_<%= commentable.id %>_cell_new_comment" class="cell_comments_new card">
    <div class="card-header">发表新评论</div>
    <%= form_with(model: new_comment, remote: true, html: { class: "card-body" }) do |f| %>
      <%= f.hidden_field :commentable_type %>
      <%= f.hidden_field :commentable_id %>
      <div class="form-group">
        <%= f.text_area :body, :class => "form-control", :rows => "3" %>
      </div>
      <div class="buttons">
        <%= f.submit t("comments.create_comment"), :class => "btn btn-primary", 'data-disable-with' => t("common.saving") %> <span class="help-inline">Ctrl+Enter</span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_editor_help_block.html.erb
<ul>
  <li>支持 Markdown 格式, <strong>**粗体**</strong>、~~删除线~~、<code>`单行代码`</code></li>
  <li>支持表情，见 <a href="http://www.emoji-cheat-sheet.com" target="_blank" rel="nofollow">Emoji cheat sheet</a></li>
  <li>按 “M” 键查看更多 <a href="#markdown_help_tip_modal" data-toggle="modal" data-keyboard="true" data-backdrop="true">帮助</a></li>
  <li>注意单词拼写，以及中英文排版，<a href="https://github.com/sparanoid/chinese-copywriting-guidelines" target="_blank">参考此页</a>
</ul>

<div class="modal fade" id="markdown_help_tip_modal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h4>格式说明</h4>
      </div>
      <div class="modal-body">
        <ul>
          <li>支持 Markdown 格式</li>
          <li><strong>**粗体**</strong>、~~删除线~~、<code>`单行代码`</code></li>
          <li>http://example.org 自动加链接</li>
          <li>@name  会链接到用户页面，并会通知他</li>
          <li>![Alt text here](http://foo.com/bar.jpg) 显示图片</li>
          <li>多行代码格式，使用 3 个`包起来，注意要换行，第一个 ``` 后面接语言名称(ruby,bash,html,css,python,erb,java... <a href="http://pygments.org/docs/lexers/" target="_blank">更多</a>)<br />
            比如这样：
              <pre style="border:0;background:#FFF;margin:0;">```ruby
    class Hello
    end
    ```</pre>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_editor_toolbar.html.erb
<div class="editor-toolbar clearfix">
  <div class="reply-to pull-right" style="display:none;">
    <i class="fa fa-mail-reply" title="回复"></i>
    <a href="#" class="user"></a>
    <a href="#" class="close"><i class="fa fa-close"></i></a>
  </div>
  <div class="opts">
    <a href="#" class="nav-link pickup-emoji"><i class="fa fa-smile-o"></i></a>
    <% if Setting.has_module? 'editor.code' %>
    <span class="dropdown" id="dropdown-insert-codes">
      <a href="#editor-toolbar-insert-code" class="nav-link dropdown-toggle" data-toggle="dropdown" title="<%= t("common.editor_insert_codes") %>"><i class="fa fa-code"></i></a>
      <div class="dropdown-menu insert-codes" aria-labelledby="dropdown-insert-codes">
        <%= insert_code_menu_items_tag %>
      </div>
    </span>
    <% end %>
    <%= link_to icon_tag("image"), "#", id: "editor-upload-image", title: t("common.editor_add_image"), class: "nav-link" %>
    <a href="#" class="nav-link preview"><%= t("common.editor_toolbar_preview") %></a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="alert alert-block alert-danger">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <div><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_hot_locations.html.erb
<% cache(["index-locations",Time.now.strftime("%Y-%m-%d")]) do %>
  <div class="index-locations card">
    <div class="card-header"><%=t("common.hot_locations")%></div>
    <div class="card-body location-list" style="text-align:center;">
      <% Location.hot.limit(12).each do |item| %>
        <span class="name"><%= location_name_tag(item) %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_index_sections.html.erb
<% cache(["index_locations", CacheVersion.section_node_updated_at]) do %>
<div class="index-sections card">
  <div class="card-header"><%= t("common.index_node_navigation")%></div>
  <div class="card-body">
    <div class="row node-list">
      <% Section.includes(:nodes).all.each do |section| %>
      <div class="node media">
        <label class="mr-2 media-left"><%= section.name %></label>
        <span class="nodes media-body">
          <% section.nodes.sorted.each do |node| %>
            <span class="name"><%= link_to(node.name, node_topics_path(node), title: node.name, data: { id: node.id })%></span>
          <% end %>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<ul id="main-nav-menu" class="navbar-nav d-flex">
  <%= render_list_items do |li|
    li << link_to(t("menu.topics"), Setting.has_module?(:home) ? main_app.topics_path : main_app.root_path, class: "nav-link")

    Homeland.navbar_plugins.each do |plugin|
      li << link_to(plugin.display_name, plugin.root_path, class: "nav-link") if Setting.has_module?(plugin.name)
    end
  end %>
  <%= raw Setting.navbar_html %>
</ul>

app/views/shared/_usernav.html.erb
<ul class="nav navbar-nav user-bar align-items-center justify-content-end">
  <% if current_user %>
  <%
  badge_class = ""
  badge_class = "new" if unread_notify_count > 0
  %>
  <li class="nav-item notification-count">
    <a href="<%= main_app.notifications_path %>" class="nav-link <%= badge_class %>" title="通知"><i class="fa fa-bell"></i><span class="count"><%= unread_notify_count %></span></a>
  </li>
  <li class="nav-item dropdown">
    <a href="#" id="navbar-new-menu" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-plus"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-new-menu">
      <%= link_to t("topics.new_topic"), main_app.new_topic_path, class: "dropdown-item" %>
      <% if can?(:create, Team) && Setting.has_module?(:team) %>
        <div class="dropdown-divider"></div>
        <%= link_to t("teams.new_team"), main_app.new_team_path, class: "dropdown-item" %>
      <% end %>
    </div>
  </li>
  <% end %>

  <% if current_user %>
    <li class="nav-item dropdown dropdown-avatar">
      <a href="#" class="dropdown-toggle nav-link" id="navbar-user-menu" data-toggle="dropdown" role="button" aria-expanded="false">
        <%= user_avatar_tag(current_user, :sm, link: false) %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-user-menu">
        <%= link_to current_user.login, main_app.user_path(current_user), class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to t("menu.edit_account_path"), main_app.setting_path, class: "dropdown-item" %>
        <%= link_to t("menu.likes"), main_app.favorites_topics_path, class: "dropdown-item" %>
        <% Homeland.user_menu_plugins.each do |plugin| %>
          <%= link_to plugin.display_name, plugin.root_path, class: "dropdown-item" %>
        <% end %>

        <% if admin? %>
          <div class="dropdown-divider"></div>
          <% if params[:controller].start_with?("admin/") %>
            <%= link_to "回到前台", main_app.root_path, class: "dropdown-item" %>
          <% else %>
            <%= link_to "管理后台", main_app.admin_root_path, class: "dropdown-item" %>
          <% end %>
        <% end %>

        <div class="dropdown-divider"></div>
        <%= link_to t("common.logout"), main_app.destroy_user_session_path, method: "delete", class: "dropdown-item" %>
      </div>
    </li>
  <% else %>
    <% if !Setting.sso_enabled? %>
    <li class="nav-item"><%= link_to t("common.register"), main_app.new_user_registration_path, class: "nav-link" %></li>
    <% end %>

    <li class="nav-item"><%= link_to t("common.login"), main_app.new_user_session_path, class: "nav-link" %></li>
  <% end %>
</ul>